[View in Colaboratory](https://colab.research.google.com/github/Ishikaaa/ML_Assignment-1/blob/master/ML_Ass4(pandas1).ipynb)

In [21]:
#Q1.
import pandas as pd 
import numpy as np 
df=pd.DataFrame(
    {"Name":['Ishika Garg','Aman'],
     'Age':[18,19],
     'mail_id':['gargishika1998@gmail.com','aman19@gmail.com'],
     'phone_number':['8688686866','6866686866']}
   )
print(df)
n=len(df.index)

   Age         Name                   mail_id phone_number
0   18  Ishika Garg  gargishika1998@gmail.com   8688686866
1   19         Aman          aman19@gmail.com   6866686866

In [22]:
#adding data to dataframe 
print(n)
a=input("enter your name=")
b=int(input("Enter your age="))
c=input("Enter your mail id=")
d=input("Enter your phone number=")
df.loc[n]=[a,b,c,d]
print(df)

2
enter your name=raman
Enter your age=12
Enter your mail id=raman12@gmail.com
Enter your phone number=1111111111
      Age         Name                   mail_id phone_number
0      18  Ishika Garg  gargishika1998@gmail.com   8688686866
1      19         Aman          aman19@gmail.com   6866686866
2  raman            12         raman12@gmail.com   1111111111

In [24]:
#importing dataset
df1=pd.read_csv("https://raw.githubusercontent.com/Shreyas3108/Weather/master/weather.csv")
print(df1)

           Date  Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0     11/1/2007  Canberra      8.0     24.3       0.0          3.4       6.3
1     11/2/2007  Canberra     14.0     26.9       3.6          4.4       9.7
2     11/3/2007  Canberra     13.7     23.4       3.6          5.8       3.3
3     11/4/2007  Canberra     13.3     15.5      39.8          7.2       9.1
4     11/5/2007  Canberra      7.6     16.1       2.8          5.6      10.6
5     11/6/2007  Canberra      6.2     16.9       0.0          5.8       8.2
6     11/7/2007  Canberra      6.1     18.2       0.2          4.2       8.4
7     11/8/2007  Canberra      8.3     17.0       0.0          5.6       4.6
8     11/9/2007  Canberra      8.8     19.5       0.0          4.0       4.1
9    11/10/2007  Canberra      8.4     22.8      16.2          5.4       7.7
10   11/11/2007  Canberra      9.1     25.2       0.0          4.2      11.9
11   11/12/2007  Canberra      8.5     27.3       0.2          7.2      12.5
12   11/13/2007  Canberra     10.1     27.9       0.0          7.2      13.0
13   11/14/2007  Canberra     12.1     30.9       0.0          6.2      12.4
14   11/15/2007  Canberra     10.1     31.2       0.0          8.8      13.1
15   11/16/2007  Canberra     12.4     32.1       0.0          8.4      11.1
16   11/17/2007  Canberra     13.8     31.2       0.0          7.2       8.4
17   11/18/2007  Canberra     11.7     30.0       1.2          7.2      10.1
18   11/19/2007  Canberra     12.4     32.3       0.6          7.4      13.0
19   11/20/2007  Canberra     15.6     33.4       0.0          8.0      10.4
20   11/21/2007  Canberra     15.3     33.4       0.0          8.8       9.5
21   11/22/2007  Canberra     16.4     19.4       0.4          9.2       0.0
22   11/23/2007  Canberra     12.8     18.5      25.8          2.8       0.6
23   11/24/2007  Canberra     12.0     24.3       0.4          1.2       7.5
24   11/25/2007  Canberra     15.4     28.4       0.0          4.4       8.1
25   11/26/2007  Canberra     15.6     26.9       0.0          6.8       8.9
26   11/27/2007  Canberra     13.3     22.2       0.2          6.6       2.3
27   11/28/2007  Canberra     12.9     28.0       0.0          4.4      10.7
28   11/29/2007  Canberra     15.1     24.3       0.0          7.0       0.4
29   11/30/2007  Canberra     13.6     24.1       0.4          2.6       0.5
..          ...       ...      ...      ...       ...          ...       ...
336   10/2/2008  Canberra      5.6     27.6       0.0          5.2      11.0
337   10/3/2008  Canberra     16.8     28.9       0.0         10.0      10.8
338   10/4/2008  Canberra     14.4     20.7       7.6          9.4       4.9
339   10/5/2008  Canberra     10.3     21.3       3.0          4.2       6.7
340   10/6/2008  Canberra     11.2     18.0       0.0          4.8       8.4
341   10/7/2008  Canberra      0.3     16.0       8.2          5.4      11.8
342   10/8/2008  Canberra      0.5     17.9       0.0          5.8      11.5
343   10/9/2008  Canberra      0.5     20.0       0.0          6.2      11.5
344  10/10/2008  Canberra      4.6     22.0       0.0          4.4      11.0
345  10/11/2008  Canberra      8.2     22.4       0.0          5.4      11.2
346  10/12/2008  Canberra      4.5     23.9       0.0          4.8      11.7
347  10/13/2008  Canberra      6.7     26.1       0.0          6.2       7.5
348  10/14/2008  Canberra     11.9     21.1      13.2          6.6       NaN
349  10/15/2008  Canberra      9.2     19.6       0.6          3.4      10.4
350  10/16/2008  Canberra      4.4     21.0       0.0          4.2      12.2
351  10/17/2008  Canberra      5.0     24.1       0.0          6.2      12.0
352  10/18/2008  Canberra      6.7     24.7       0.0          5.4       8.6
353  10/19/2008  Canberra      8.3     28.5       0.0          5.8       9.8
354  10/20/2008  Canberra     11.3     27.4       0.2          7.6      12.1
355  10/21/2008  Canberra      9.0     20.6       0.0          9.0       6.2
356  10/22/2008  Canberra      3.4     15.0       0.8          4.8      11.7
357  10/23/2008  Canberra      3.2     18.0       0.0          7.4      12.2
358  10/24/2008  Canberra      0.9     20.7       0.0          5.4       8.4
359  10/25/2008  Canberra      3.3     25.5       0.0          5.2      10.8
360  10/26/2008  Canberra      7.9     26.1       0.0          6.8       3.5
361  10/27/2008  Canberra      9.0     30.7       0.0          7.6      12.1
362  10/28/2008  Canberra      7.1     28.4       0.0         11.6      12.7
363  10/29/2008  Canberra     12.5     19.9       0.0          8.4       5.3
364  10/30/2008  Canberra     12.5     26.9       0.0          5.0       7.1
365  10/31/2008  Canberra     12.3     30.2       0.0          6.0      12.6

    WindGustDir  WindGustSpeed WindDir9am      ...      Humidity3pm  \
0            NW           30.0         SW      ...               29
1           ENE           39.0          E      ...               36
2            NW           85.0          N      ...               69
3            NW           54.0        WNW      ...               56
4           SSE           50.0        SSE      ...               49
5            SE           44.0         SE      ...               57
6            SE           43.0         SE      ...               47
7             E           41.0         SE      ...               57
8             S           48.0          E      ...               48
9             E           31.0          S      ...               32
10            N           30.0         SE      ...               34
11            E           41.0          E      ...               35
12          WNW           30.0          S      ...               29
13           NW           44.0        WNW      ...               20
14           NW           41.0          S      ...               16
15            E           46.0         SE      ...               22
16          ESE           44.0        WSW      ...               23
17            S           52.0         SW      ...               26
18            E           39.0        NNE      ...               25
19           NE           33.0        NNW      ...               27
20          WNW           59.0          N      ...               26
21            E           26.0        ENE      ...               72
22          ESE           28.0          S      ...               79
23          NNE           26.0        WSW      ...               57
24          ENE           33.0        SSE      ...               31
25            E           41.0          E      ...               48
26          ENE           39.0          E      ...               55
27            S           52.0          S      ...               31
28           SE           39.0         SE      ...               80
29          NNW           30.0        SSW      ...               49
..          ...            ...        ...      ...              ...
336          NW           46.0        NNW      ...               21
337         NNW           70.0         NW      ...               22
338         NNW           33.0        NNW      ...               65
339         NNW           43.0        ENE      ...               46
340           W           65.0          N      ...               40
341          NW           57.0        NNW      ...               45
342           N           44.0        NNE      ...               33
343         NNW           31.0          S      ...               22
344           N           41.0        NNW      ...               25
345          NW           31.0        SSW      ...               30
346          NW           30.0        ENE      ...               27
347         SSW           70.0         NE      ...               47
348          NW           41.0        NNE      ...               61
349         ENE           31.0        SSE      ...               42
350          NW           28.0         SW      ...               30
351         NNW           52.0        NaN      ...               34
352          NW           43.0          N      ...               31
353          NW           46.0          W      ...               30
354          NW           52.0         SE      ...               20
355         ENE           39.0          S      ...               28
356           S           70.0          S      ...               24
357         SSE           48.0        SSE      ...               25
358         NNW           39.0        SSE      ...               29
359           N           43.0          N      ...               16
360         NNW           43.0        NaN      ...               20
361         NNW           76.0        SSE      ...               15
362           N           48.0        NNW      ...               22
363         ESE           43.0        ENE      ...               47
364          NW           46.0        SSW      ...               39
365          NW           78.0         NW      ...               13

     Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  \
0         1019.7       1015.0         7         7     14.4     23.6
1         1012.4       1008.4         5         3     17.5     25.7
2         1009.5       1007.2         8         7     15.4     20.2
3         1005.5       1007.0         2         7     13.5     14.1
4         1018.3       1018.5         7         7     11.1     15.4
5         1023.8       1021.7         7         5     10.9     14.8
6         1024.6       1022.2         4         6     12.4     17.3
7         1026.2       1024.2         6         7     12.1     15.5
8         1026.1       1022.7         7         7     14.1     18.9
9         1024.1       1020.7         7         1     13.3     21.7
10        1024.4       1021.1         1         2     14.6     24.0
11        1023.8       1019.9         0         3     16.8     26.0
12        1022.0       1017.1         0         1     17.0     27.1
13        1017.3       1013.1         1         4     19.7     30.7
14        1018.2       1013.7         0         1     18.7     30.4
15        1017.9       1012.8         0         3     19.1     30.7
16        1014.4       1009.8         7         6     20.2     29.8
17        1016.4       1013.0         1         5     20.1     28.6
18        1017.1       1013.3         1         3     20.2     31.2
19        1018.5       1013.7         0         1     22.8     32.0
20        1012.4       1006.5         1         5     22.2     32.8
21        1010.7       1008.9         8         8     16.5     18.3
22        1014.0       1014.9         8         8     14.0     16.8
23        1020.7       1019.2         7         5     17.8     22.8
24        1022.4       1018.6         8         2     16.8     27.3
25        1019.7       1016.5         2         4     19.8     25.1
26        1021.0       1018.6         7         7     16.5     21.2
27        1019.2       1014.8         5         7     18.8     26.7
28        1019.0       1017.1         7         7     18.9     19.7
29        1017.2       1013.3         8         7     17.3     23.2
..           ...          ...       ...       ...      ...      ...
336       1017.7       1014.1         0         0     19.0     26.7
337       1016.3       1011.8         1         1     22.5     28.4
338       1015.5       1013.2         8         4     14.5     19.3
339       1018.1       1013.6         8         1     11.7     19.8
340       1009.5       1005.3         5         4     12.8     16.2
341       1016.8       1013.3         1         1      6.9     14.6
342       1019.1       1017.5         0         1      7.2     16.6
343       1026.2       1024.2         0         1      8.1     18.8
344       1028.8       1024.9         1         2     10.0     21.4
345       1027.8       1023.8         1         3     13.6     20.6
346       1025.8       1021.5         0         4     12.6     22.3
347       1020.9       1016.0         4         7     16.3     23.2
348       1019.2       1016.7         7         3     14.5     19.4
349       1022.3       1019.7         7         4     11.6     18.4
350       1025.7       1022.3         1         1      9.6     19.2
351       1024.5       1020.7         6         1     11.6     21.9
352       1025.7       1022.2         1         7     12.7     23.7
353       1024.1       1019.8         1         6     16.8     27.4
354       1021.4       1017.5         1         1     16.4     26.3
355       1022.3       1018.6         7         5     11.4     18.5
356       1023.4       1023.1         1         5      8.3     14.3
357       1026.6       1022.8         1         2      9.1     16.3
358       1023.2       1018.4         3         8      9.4     19.1
359       1018.8       1014.6         0         3     12.0     24.8
360       1017.6       1014.2         5         8     16.3     25.9
361       1016.1       1010.8         1         3     20.4     30.0
362       1020.0       1016.9         0         1     17.2     28.2
363       1024.0       1022.8         3         2     14.5     18.3
364       1021.0       1016.2         6         7     15.8     25.9
365       1009.6       1009.2         1         1     23.8     28.6

     RainToday  RISK_MM  RainTomorrow
0           No      3.6           Yes
1          Yes      3.6           Yes
2          Yes     39.8           Yes
3          Yes      2.8           Yes
4          Yes      0.0            No
5           No      0.2            No
6           No      0.0            No
7           No      0.0            No
8           No     16.2           Yes
9          Yes      0.0            No
10          No      0.2            No
11          No      0.0            No
12          No      0.0            No
13          No      0.0            No
14          No      0.0            No
15          No      0.0            No
16          No      1.2           Yes
17         Yes      0.6            No
18          No      0.0            No
19          No      0.0            No
20          No      0.4            No
21          No     25.8           Yes
22         Yes      0.4            No
23          No      0.0            No
24          No      0.0            No
25          No      0.2            No
26          No      0.0            No
27          No      0.0            No
28          No      0.4            No
29          No     22.6           Yes
..         ...      ...           ...
336         No      0.0            No
337         No      7.6           Yes
338        Yes      3.0           Yes
339        Yes      0.0            No
340         No      8.2           Yes
341        Yes      0.0            No
342         No      0.0            No
343         No      0.0            No
344         No      0.0            No
345         No      0.0            No
346         No      0.0            No
347         No     13.2           Yes
348        Yes      0.6            No
349         No      0.0            No
350         No      0.0            No
351         No      0.0            No
352         No      0.0            No
353         No      0.2            No
354         No      0.0            No
355         No      0.8            No
356         No      0.0            No
357         No      0.0            No
358         No      0.0            No
359         No      0.0            No
360         No      0.0            No
361         No      0.0            No
362         No      0.0            No
363         No      0.0            No
364         No      0.0            No
365         No      0.0            No

[366 rows x 24 columns]

In [25]:
#first 5 rows of a dataframe 
df1.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,11/1/2007,Canberra,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,11/2/2007,Canberra,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,11/3/2007,Canberra,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,11/4/2007,Canberra,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,11/5/2007,Canberra,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No

In [26]:
#first 10 rows of a dataframe 
df1.head(10)

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,11/1/2007,Canberra,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,11/2/2007,Canberra,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,11/3/2007,Canberra,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,11/4/2007,Canberra,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,11/5/2007,Canberra,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No
5,11/6/2007,Canberra,6.2,16.9,0.0,5.8,8.2,SE,44.0,SE,...,57,1023.8,1021.7,7,5,10.9,14.8,No,0.2,No
6,11/7/2007,Canberra,6.1,18.2,0.2,4.2,8.4,SE,43.0,SE,...,47,1024.6,1022.2,4,6,12.4,17.3,No,0.0,No
7,11/8/2007,Canberra,8.3,17.0,0.0,5.6,4.6,E,41.0,SE,...,57,1026.2,1024.2,6,7,12.1,15.5,No,0.0,No
8,11/9/2007,Canberra,8.8,19.5,0.0,4.0,4.1,S,48.0,E,...,48,1026.1,1022.7,7,7,14.1,18.9,No,16.2,Yes
9,11/10/2007,Canberra,8.4,22.8,16.2,5.4,7.7,E,31.0,S,...,32,1024.1,1020.7,7,1,13.3,21.7,Yes,0.0,No

In [29]:
#statistics of Mintemp
df1['MinTemp'].describe()

count    366.000000
mean       7.265574
std        6.025800
min       -5.300000
25%        2.300000
50%        7.450000
75%       12.500000
max       20.900000
Name: MinTemp, dtype: float64

In [30]:
#statistics of Maxtemp
df1['MaxTemp'].describe()

count    366.000000
mean      20.550273
std        6.690516
min        7.600000
25%       15.025000
50%       19.650000
75%       25.500000
max       35.800000
Name: MaxTemp, dtype: float64

In [31]:
#last 5 rows of a dataframe 
df1.tail()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
361,10/27/2008,Canberra,9.0,30.7,0.0,7.6,12.1,NNW,76.0,SSE,...,15,1016.1,1010.8,1,3,20.4,30.0,No,0.0,No
362,10/28/2008,Canberra,7.1,28.4,0.0,11.6,12.7,N,48.0,NNW,...,22,1020.0,1016.9,0,1,17.2,28.2,No,0.0,No
363,10/29/2008,Canberra,12.5,19.9,0.0,8.4,5.3,ESE,43.0,ENE,...,47,1024.0,1022.8,3,2,14.5,18.3,No,0.0,No
364,10/30/2008,Canberra,12.5,26.9,0.0,5.0,7.1,NW,46.0,SSW,...,39,1021.0,1016.2,6,7,15.8,25.9,No,0.0,No
365,10/31/2008,Canberra,12.3,30.2,0.0,6.0,12.6,NW,78.0,NW,...,13,1009.6,1009.2,1,1,23.8,28.6,No,0.0,No

In [37]:
#Extract column from a dataset 
s1=df1['Evaporation']
print("*"*50+"EVAPORATION"+"*"*50)
print(s1)
#applying statistics on s1
print("*"*50+"APPLYING STATISTICS"+"*"*50)
s1.describe()

**************************************************EVAPORATION**************************************************
0       3.4
1       4.4
2       5.8
3       7.2
4       5.6
5       5.8
6       4.2
7       5.6
8       4.0
9       5.4
10      4.2
11      7.2
12      7.2
13      6.2
14      8.8
15      8.4
16      7.2
17      7.2
18      7.4
19      8.0
20      8.8
21      9.2
22      2.8
23      1.2
24      4.4
25      6.8
26      6.6
27      4.4
28      7.0
29      2.6
       ...
336     5.2
337    10.0
338     9.4
339     4.2
340     4.8
341     5.4
342     5.8
343     6.2
344     4.4
345     5.4
346     4.8
347     6.2
348     6.6
349     3.4
350     4.2
351     6.2
352     5.4
353     5.8
354     7.6
355     9.0
356     4.8
357     7.4
358     5.4
359     5.2
360     6.8
361     7.6
362    11.6
363     8.4
364     5.0
365     6.0
Name: Evaporation, Length: 366, dtype: float64
**************************************************APPLYING STATISTICS**************************************************

count    366.000000
mean       4.521858
std        2.669383
min        0.200000
25%        2.200000
50%        4.200000
75%        6.400000
max       13.800000
Name: Evaporation, dtype: float64

In [38]:
#Extract column from a dataset 
s2=df1['Temp9am']
print("*"*50+"TEMP9AM"+"*"*50)
print(s2)
#applying statistics on s1
print("*"*50+"APPLYING STATISTICS"+"*"*50)
s1.describe()

**************************************************TEMP9AM**************************************************
0      14.4
1      17.5
2      15.4
3      13.5
4      11.1
5      10.9
6      12.4
7      12.1
8      14.1
9      13.3
10     14.6
11     16.8
12     17.0
13     19.7
14     18.7
15     19.1
16     20.2
17     20.1
18     20.2
19     22.8
20     22.2
21     16.5
22     14.0
23     17.8
24     16.8
25     19.8
26     16.5
27     18.8
28     18.9
29     17.3
       ...
336    19.0
337    22.5
338    14.5
339    11.7
340    12.8
341     6.9
342     7.2
343     8.1
344    10.0
345    13.6
346    12.6
347    16.3
348    14.5
349    11.6
350     9.6
351    11.6
352    12.7
353    16.8
354    16.4
355    11.4
356     8.3
357     9.1
358     9.4
359    12.0
360    16.3
361    20.4
362    17.2
363    14.5
364    15.8
365    23.8
Name: Temp9am, Length: 366, dtype: float64
**************************************************APPLYING STATISTICS**************************************************

count    366.000000
mean       4.521858
std        2.669383
min        0.200000
25%        2.200000
50%        4.200000
75%        6.400000
max       13.800000
Name: Evaporation, dtype: float64